 import java.util.*;

// You are given two strings, s and t which only consist of lowercase letters.
 // t is generated by shuffling the letters in s as well as potentially adding an
 // additional random character. Return the letter that was randomly added to t if it exists,

public class program {
    public static void main(String[] args)
    {
        String s = "foobar";
        String t = "barfoot";

        System.out.println(spotDifference(s, t));

    }

    //Time O(2n) | Space O(n)
    public static char spotDifference(String s, String t) {

        HashMap<Character, Integer> count = new HashMap<>();

        for (char c : s.toCharArray()) {
            count.put(c, count.getOrDefault(c, 0) + 1);
        }

        for (char c : t.toCharArray()) {
            if (count.containsKey(c) && count.get(c) == 0 || !count.containsKey(c))
                return c;
            else
                count.put(c, count.get(c) - 1);
        }

        return '!';
    }
}
